select pp.IDPROGRAMA, pp.IDPREDMETA, p1.NAZIV, pp.VRSTA, up.IDUSLOVNOGPREDMETA, p2.NAZIV
from DA.PREDMETPROGRAMA pp left join DA.USLOVNIPREDMET up
    on pp.IDPREDMETA = up.IDPREDMETA and pp.IDPROGRAMA = up.IDPROGRAMA
    join DA.PREDMET p1 on pp.IDPREDMETA = p1.ID
    left join DA.PREDMET p2 on up.IDUSLOVNOGPREDMETA = p2.ID
