create table test (
    id integer not null primary key generated by default as identity (start with 100, increment by 2),
    slovo char
);

insert into test(slovo)
values ('a');

insert into test
values (2, 'b');

insert into test(slovo)
values ('c');

drop table test;
